language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_script:
  - composer install --dev
  - composer require --dev kherge/box

script:
    - phpunit
    - |
        if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then
            vendor/bin/box build
            ls -la build
        fi
